### ISSUE TITLE
Stopped working in Flutter 3.10 - accentColor deprecated

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [kevlatus/flutter_fortune_wheel#103]
**Describe the bug**
As Flutter 3.10 removed accentColor, the package stopped working.

This should be fixed by #102 

**To Reproduce**
1. Depend on this package
2. Try to run app

**Expected behavior**
The app runs properly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Not Applicable / Run in Android 13 Emulator
 - Version: Flutter 3.10

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - Browser: Chrome

**Comment by rajaarav0** [comment]
Any update when it will be fixed?

**Comment by kevlatus** [comment]
thanks for the comments and the pull requests. v1.2.1 has just been published, which includes the changes for colorScheme.accentColor
