### ISSUE TITLE
FlutterError (setState() or markNeedsBuild() called during build when calling setState in onFocusItemChanged

### ISSUE THREAD

**Issue by nelci592** [kevlatus/flutter_fortune_wheel#114]
When using setState in onFocusItemChanged. For example:
        onFocusItemChanged: (int index) {
                      setState(() {
                        _isLifted = !_isLifted;
                      });
                    },
I get the following error:
FlutterError (setState() or markNeedsBuild() called during build.
This FortuneWheelView widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

**Comment by winter-tech** [comment]
I also encountered this problem. I wanted to display the results on the turntable, but the results would keep scrolling, but an error occurred.
