### ISSUE TITLE
Make spin not stop on center

### ISSUE THREAD

**Issue by chitoadinugraha** [kevlatus/flutter_fortune_wheel#123]
**Is your feature request related to a problem? Please describe.**
The spinning wheel indicator always stop on center,

**Describe the solution you'd like**
The spinning wheel indicator not always stop on center of FortuneItem. maybe use double as StreamController value?

**Comment by stor-gang** [comment]
@kevlatus can you please reply to this? it would be nice feature to have. Thanks
