### ISSUE TITLE
selected property

### ISSUE THREAD

**Issue by mado-bohsali** [kevlatus/flutter_fortune_wheel#36]
I am using if else statements to force stop the indicator at certain numbers
I noticed that if selected ==0 and I already stopped at 0, it doesn't animate anymore

Why?

**Comment by kevlatus** [comment]
Hi @mado-bohsali,

the reason for this is explained in #37, which also includes a change to this behavior. I still need to do some testing, before this update can be considered stable, but you can already try it in the [prelease version 1.0.0-dev.0](https://pub.dev/packages/flutter_fortune_wheel/versions/1.0.0-dev.0).

I suppose this resolves your issue. If it doesn't, please comment.
