### ISSUE TITLE
Extra Central Widget in Spinner

### ISSUE THREAD

**Issue by mado-bohsali** [kevlatus/flutter_fortune_wheel#38]
![image](https://user-images.githubusercontent.com/18421260/110619897-0d6e9200-81a1-11eb-8641-5dc6f791d8b7.png)

Can I insert a widget into the center of the spinner (other than the indicator) as depicted in the image above?

**Comment by kevlatus** [comment]
Hi @mado-bohsali,

I see two ways you can achieve this:
1. wrap both wheel and image in a Stack
```dart
Stack(
  alignment: Alignment.center,
  children: [
    FortuneWheel(/* ... */),
    Container(color: Colors.red, width: 48, height: 48), // <-- replace this with your centered widget
  ],
)
```

2. add a second custom indicator with `Alignment.center`
```dart
FortuneWheel(
  /* ... */
  indicators: [
    FortuneIndicator(
      alignment: Alignment.topCenter,
      child: TriangleIndicator(),
    ),
    FortuneIndicator(
      alignment: Alignment.center,
      child: Container(color: Colors.red, width: 48, height: 48),  // <-- replace this with your centered widget
    ),
  ],
)
```

Is this what you are looking for?

**Comment by mado-bohsali** [comment]
Amazing! Thanks for the tip. I was wondering if I could have a call with you and share my screen to discuss my custom logic behind tapping the wheel. In brief, I have a set of questions having each has its category label as well as the spinner. I want to force the spinner to stop at a category so that I fetch a question onAnimationEnd.

**Comment by kevlatus** [comment]
@mado-bohsali: please provide a minimal repo, which reproduces your error. Without seeing the error-causing code, I am unable to debug

**Comment by mado-bohsali** [comment]
Please find attached this compressed project. Notice that sometimes the spinner doesn’t spin because the value of selected variable is the same before and after animation.


Your latest version is used. 

Should I use onFling() with the same logic as on gesture tap?

Best,
Mohamad

**Comment by kevlatus** [comment]
Hi @mado-bohsali,

your code sample doesn't use the pre-release version, which fixes this issue. Can you please follow [these instructions](https://pub.dev/packages/flutter_fortune_wheel/versions/1.0.0-dev.0/install) and use [these samples](https://pub.dev/packages/flutter_fortune_wheel/versions/1.0.0-dev.0) in order to solve it.

Yes, you can use onFling this way, if you want the wheel to spin, when a user drags it on the screen.

Best
Kevin

**Comment by mado-bohsali** [comment]
It’s working as expected. Thank you. 

Does it cause problems with Flutter 2.0.2?

**Comment by mado-bohsali** [comment]
Stack-overflow discussions:
You could use broadcast, which allows to listen stream more than once, but it also prevents from listening past events

The package is working smoothly thanks man!
Appreciate it

**Comment by kevlatus** [comment]
good to hear! I haven't seen any issues with latest Flutter versions, since the package was just migrated to Flutter 2.

Which type of stream you use, is up to you, but I see StackOverflow got your back on that one.

Thanks for using it!

**Comment by mado-bohsali** [comment]
Thanks and have a nice weekend!
Awaiting your future packages!
