### ISSUE TITLE
Visual bug, if there are only 2 elements, the selector does not point correctly

### ISSUE THREAD

**Issue by rusudinu** [kevlatus/flutter_fortune_wheel#39]
**Describe the bug**
If there are only 2 elements to choose from, then the selected arrows for the FortuneBar will be exactly between the two.
Plugin version: 0.4.2 & 1.0.0-dev.0 (tested both)

**Expected behavior**
Only one Item to be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/35799602/117037440-24e47a00-ad0f-11eb-94c6-cc5560c2e94a.png)

**Smartphone (please complete the following information):**
 - Device: Android Emulator (Nexus 5X api lvl 29)
 - OS: Android 10

**Additional context**
```
selectedRandomOption = Random().nextInt(_options.length);
```
[...]
```
FortuneBar(
        selected: selectedRandomOption, //selected: Stream.value(selectedRandomOption), <- for 1.0.0-dev.0 version of the plugin
         items: _options .map((e) => FortuneItem(child: Text(e),)).toList(),
),
```

**Comment by kevlatus** [comment]
Thanks for pointing that out, @rusudinu!
v1.0.0 is currently being published, which should fix this issue
