### ISSUE TITLE
force spin the wheel when selected item is the same after random

### ISSUE THREAD

**Issue by kotori94** [kevlatus/flutter_fortune_wheel#49]
Hi, I notice that after randomizing a new selected result in item range, if the result is different from the current selected, the wheel spins and works as expected.

But the problem is when the new random is still the same (eg: 0 and 0), the wheel does not spin at all. How do I force the wheel spin in this case?

Thanks

**Comment by kevlatus** [comment]
Hi @kotori94,
this was actually an issue of versions prior to v1.0.0, which introduced a new stream-based API for selecting items. You can install it like this:
```yaml
dependencies:
  flutter_fortune_wheel: ^1.0.0
```
and find [a code example here](https://pub.dev/packages/flutter_fortune_wheel#quick-start).

Using a StreamController, the wheel will spin, even if the selected item doesn't change.

**Comment by kotori94** [comment]
hi @kevlatus, i am currently using flutter v1.2.26 for production. could you please give me the code that update stream based api for selecting item? I really need it to work on 1.2.26 because my app has launched production quite long :(
