### ISSUE TITLE
Add Custom Color and Custom Pointer

### ISSUE THREAD

**Issue by MuhammadRasyiddin** [kevlatus/flutter_fortune_wheel#5]

**Comment by kevlatus** [comment]
Hi Muhammad, thanks for reaching out!

Custom colors are already possible like this:
```dart
FortuneWheel(
  selected: 0,
  indicators: [
    // indicator customization
    FortuneWheelIndicator(
      child: TriangleIndicator(),
      color: Colors.white, // <-- custom indicator color
    ),
  ],
  slices: [
    CircleSlice(
      child: Text('A'),
      fillColor: Colors.red, // <-- custom circle slice fill color
      strokeColor: Colors.green, // <-- custom circle slice stroke color
      strokeWidth: 3, // <-- custom circle slice stroke width
    ),
    CircleSlice(
      child: Text('B'),
      fillColor: Colors.blue,
      strokeColor: Colors.yellow,
      strokeWidth: 1,
    ),
  ],
)
```

Can you explain what you mean by custom pointer? If you refer to the triangle indicator, above code also shows you how to customize it.

**Comment by berkegokmen1** [comment]
When I try to use the code below the indicator moves to the middle. How do I prevent this?
`
FortuneIndicator(
      child: TriangleIndicator(),
      color: Colors.white, // <-- custom indicator color
    ),
`

**Comment by ibrhm-jz** [comment]
Not found :C

**Comment by mado-bohsali** [comment]
> No description provided.

Is it spinning correctly?

**Comment by ibrhm-jz** [comment]
Yes ,the problem I had was when putting color in the roulette, the
documentation is not exact for the new version

**Comment by kevlatus** [comment]
you are right, the API in my original comment has changed. I updated above comment to link to [the most recent docs](https://github.com/kevlatus/flutter_fortune_wheel#item-styling).

I suppose this fixes the issue. Please comment, if it doesn't.

**Comment by ibrhm-jz** [comment]
Thak You,that has worked for me! :)
