### ISSUE TITLE
Errto al render Wheel, in a stack

### ISSUE THREAD

**Issue by Spiderbezno** [kevlatus/flutter_fortune_wheel#50]
The following assertion was thrown building LayoutBuilder:
'package:flutter_fortune_wheel/src/wheel/slice.dart': Failed assertion: line 32 pos 16: 'radius > 0': is not true.

code
Stack(
      children: <Widget>[
        Align(
                alignment: Alignment.topCenter,
                child: SvgPicture.asset(Svgs.ruletaBorder),
              ),
       Positioned(
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                child: Padding(
                  padding: EdgeInsets.all(queryData.size.width * 0.074),
                  child: FortuneWheel(
                    animateFirst: false,
                    duration: Duration(seconds: 10),
                    indicators: <FortuneIndicator>[
                      FortuneIndicator(
                        alignment: Alignment.topCenter,
                        child: Image.asset(
                          Images.ruletaTriangle,
                          scale: 1.2,
                        ),
                      ),
                      FortuneIndicator(
                        alignment: Alignment.center,
                        child: GestureDetector(
                          onTap: () {
                            viewModel.areGeneralConditionsAccepted()
                                ? viewModel.canParticipate()
                                    ? checkIsWinner(viewModel)
                                    : _showToast(context, viewModel)
                                : _showToast(context, viewModel);
                          },
                          child: Container(
                            width: 45,
                            height: 45,
                            decoration: BoxDecoration(
                              color: AndorraTelecomColors.adicionalColor3,
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                    ],
                    physics: CircularPanPhysics(
                      duration: Duration(seconds: 1),
                      curve: Curves.decelerate,
                    ),
                    onFling: () {
                      viewModel.areGeneralConditionsAccepted()
                          ? viewModel.canParticipate()
                              ? checkIsWinner(viewModel)
                              : _showToast(context, viewModel)
                          : _showToast(context, viewModel);
                    },
                    selected: viewModel.selected.stream,
                    onAnimationEnd: () {
                      viewModel.showWidgetWinnerOrLose();
                      if (viewModel.isWinner()) {
                        _controllerTopCenter.play();
                      }
                    },
                    items: <FortuneItem>[
                      for (int i = 0; i < viewModel.items.length; i++)
                        FortuneItem(
                          child: Icon(
                            Icons.star,
                            color: i.isOdd == true ? Colors.white : AndorraTelecomColors.adicionalColor3,
                          ),
                          style: FortuneItemStyle(
                            color: i.isOdd == true ? AndorraTelecomColors.primary : AndorraTelecomColors.accent,
                            borderWidth: 0,
                            borderColor: Colors.transparent,
                          ),
                        ),
                    ],
                  ),
                ),
              ),

**Comment by kevlatus** [comment]
Hi @Spiderbezno,

the wheel needs to know its size to be properly rendered. Can you try wrapping it in a `Expanded`:

```dart
Expanded(
  child: FortuneWheel(...)
)
```

or a SizedBox depending on your overall layout:
```dart
SizedBox(
  width: 256,
  height: 256,
  child: FortuneWheel(...)
)
```

Please let me know, if that works.

**Comment by kevlatus** [comment]
Unfortunately, I can't reproduce that issue on my end and and can't execute your code as there is no minimal repo.
You can always adjust the size of a sized box to accommodate your requirements and the wheel will only take up the space it is given by its parent widget.
