### ISSUE TITLE
Option to add HapticFeedback

### ISSUE THREAD

**Issue by Spiderbezno** [kevlatus/flutter_fortune_wheel#51]
is there any option to add HapticFeedback while roulette is moving??

**Comment by kevlatus** [comment]
Hi @Spiderbezno, this is currently not implemented by the library, but could relatively easy be achieved by leveraging the [onAnimationStart](https://pub.dev/documentation/flutter_fortune_wheel/latest/flutter_fortune_wheel/FortuneWidget/onAnimationStart.html) and [onAnimationEnd](https://pub.dev/documentation/flutter_fortune_wheel/latest/flutter_fortune_wheel/FortuneWidget/onAnimationEnd.html) callbacks.
