### ISSUE TITLE
Depend on newer version of flutter_hooks

### ISSUE THREAD

**Issue by vintage** [kevlatus/flutter_fortune_wheel#52]
Latest version of flutter hooks is 0.17.0 https://pub.dev/packages/flutter_hooks
Lib depends on ^0.16.0 https://github.com/kevlatus/flutter_fortune_wheel/blob/main/pubspec.yaml#L13

Mind to bump the dependency? It will solve the issue where each project needs to override dependency on their own.

**Comment by kevlatus** [comment]
0.17.0 of flutter_hooks is now a dependency in 1.0.1 of this package
