### ISSUE TITLE
Fortune When Misalignment

### ISSUE THREAD

**Issue by mado-bohsali** [kevlatus/flutter_fortune_wheel#53]
Upon landscape view, the fortune wheel aligns to the right in Arabic locale. Not to mention, when you spin the week, it revolves wholly rather than staying in position.
 
![Simulator Screen Shot - iPhone 11 - 2021-06-18 at 15 57 32](https://user-images.githubusercontent.com/18421260/122564493-15668980-d04e-11eb-9096-4fa8ab13c452.png)

Kindly advise.
Thanks!

**Comment by kevlatus** [comment]
hey @mado-bohsali, I just published v1.0.1 on pub.dev, which should fix this issue. Can you confirm that it works on your end?

**Comment by mado-bohsali** [comment]
> hey @mado-bohsali, I just published v1.0.1 on pub.dev, which should fix this issue. Can you confirm that it works on your end?

Many thanks! It worked.

**Comment by mado-bohsali** [comment]
Worked smoothly!

Genuine wishes,

Mohamad El Bohsaly
