### ISSUE TITLE
GestureDetector within FortuneItem doesn't receive events

### ISSUE THREAD

**Issue by vintage** [kevlatus/flutter_fortune_wheel#61]
Having fortune wheel with following item:

```
FortuneItem(
                child: GestureDetector(
                  onTap: () {
                    print("XXX");
                  },
                  child: _DailyWheelItem(
                    chance: 0.03,
                    child: ResourceItem(
                      type: ResourceType.goldPremium,
                      value: 10,
                    ),
                  ),
                ),
              ),
```

and tapping on it doesn't performs the `onTap` from the `GestureDetector`. Would be great to have such option, even it disables the fling capability. I need to register tap callback to display explanation about particular item (like description and chance to hit).

![Screenshot_1624602373](https://user-images.githubusercontent.com/729785/123379880-053f3480-d58f-11eb-9478-d06589c585ed.png)

**Comment by kevlatus** [comment]
hey @vintage,

the GestureDetector won't work properly due to how the wheel is implemented. I just published v1.1.0, which includes gesture support on FortuneItems.

I hope that helps.

**Comment by vintage** [comment]
Just upgraded to `1.1.0` and the gesture detection works great now. Thanks a lot for quick fix!

**Comment by ManishPatel-Mobilefirst** [comment]
Gesture detection is not working fine (if there are only two or three Fortune Items), if i pass only two Fortune item bottom half of the Item's Detection not work..
