### ISSUE TITLE
Please add support for spin rotation speed

### ISSUE THREAD

**Issue by sguru049** [kevlatus/flutter_fortune_wheel#63]
**Describe alternatives you've considered**

**Comment by kevlatus** [comment]
Hey @sguru049,

there is the [`rotationCount`](https://pub.dev/documentation/flutter_fortune_wheel/latest/flutter_fortune_wheel/FortuneWidget/rotationCount.html) property, which implicitly determines rotation speed by setting the number of full rotations within one animation cycle.

Does that help?
