### ISSUE TITLE
Is There a Possbility To Prevent Rotation On Initialisation

### ISSUE THREAD

**Issue by komnatadeveloper** [kevlatus/flutter_fortune_wheel#68]
Hello, I appreciate for this great library.

Actually this Feature Request is not related with any problem, however, my client asks for possibility of preventing rotation on Wheel Initialization. I couldn't convince them that this isn't possible, so I would like to open an issue. (Maybe it is possible but I didn't find out how to  do. )

Thanks in advance for any kind of answers.

**Comment by kevlatus** [comment]
Hey @komnatadeveloper,

have you tried setting the [`animateFirst`](https://pub.dev/documentation/flutter_fortune_wheel/latest/flutter_fortune_wheel/FortuneWheel/animateFirst.html) option to `false`?

This should give you the expected result, if I understood correctly.

**Comment by komnatadeveloper** [comment]
Hello @kevlatus ,

Sorry, my bad :) Yes I meant thıs one, and I dıdn't notice this option.

Sorry & thank you
