### ISSUE TITLE
Question: ¿How can I align the selected item with the alignment of the Indicator?

### ISSUE THREAD

**Issue by kevingamboa17** [kevlatus/flutter_fortune_wheel#78]
This is just a simple question, ¿How can I align the selected item with the alignment of the Indicator?

Already edit the alignment of the Indicator

```
FortuneIndicator(
                    alignment: Alignment.centerRight, // <-- changing the position of the indicator
                    child: TriangleIndicator(
                      color: Colors.white54, // <-- changing the color of the indicator
                    ),
                  ),
```

But the selected item still align to topCenter? how can I change that value? 🤔 

btw congratulations and thanks on the project it has everything i need 🙌🏾  (only this little question 🙈 )

![IMG_ABED4C766854-1](https://user-images.githubusercontent.com/16912316/147498769-1d06c513-a7e5-4d20-9a4d-d22b2ce838c2.jpeg)
?

**Comment by kevlatus** [comment]
Hi @kevingamboa17, this is now included in v1.2.0 by using the [FortuneWheel.alignment parameter](https://pub.dev/documentation/flutter_fortune_wheel/latest/flutter_fortune_wheel/FortuneWheel/alignment.html)
