### ISSUE TITLE
Rotate texts after certain degree

### ISSUE THREAD

**Issue by DanielMartini** [kevlatus/flutter_fortune_wheel#80]
Hello!

Im on the situation that I need all the texts to be easy readable, this is hard after you have few items because they are upside down

is it possible to rotate the texts if they have certain degree? just like the image:

![img-wheel-256](https://user-images.githubusercontent.com/8677856/147880545-5b084a57-d85e-44f3-9f23-9579ad3410d4.png)

thanks!

**Comment by kevlatus** [comment]
Hi @DanielMartini, you can easily achieve this with code similar to the one below:

```dart
final items = [...];
return FortuneWheel(
  ...
  items: [
    for (var i = 0; i < items.length; i++)
      FortuneItem(
        child: Transform.rotate(
          angle: i > (items.length / 2) ? math.pi : 0,
          child: Text(items[i]),
        ),
      )
  ],
);

```

**Comment by DanielMartini** [comment]
That was simple, didn't notice, thanks @kevlatus!
