### ISSUE TITLE
onUpdate values

### ISSUE THREAD

**Issue by Deep-Focus-lab** [kevlatus/flutter_fortune_wheel#83]
Please ad onUpdate method for getting the progress.

**Comment by kevlatus** [comment]
Can you please specify the expected behavior of the onUpdate method?

**Comment by bjorge** [comment]
Along these lines I would like to emit a click sound each time the indicator crosses over to another slice. Thanks so much!

**Comment by berkaymazlumlar** [comment]
> Along these lines I would like to emit a click sound each time the indicator crosses over to another slice. Thanks so much!

I need something like this too. If this can be done it would be perfect

**Comment by mschmidm** [comment]
I would really appreciate that as well. Something like onUpdate(currentItem), with currentItem being the item the indicator is hovering over at that time.

**Comment by Vollinator** [comment]
Any updates for this feature?

**Comment by Natay-F** [comment]
It's been a year, any updates? Or work around?

**Comment by kevlatus** [comment]
This has finally been implemented in v1.3.0. Make sure to update and use the `FortuneWheel.onFocusItemChanged` callback
