### ISSUE TITLE
Does support for a predefined value exist?

### ISSUE THREAD

**Issue by peazz** [kevlatus/flutter_fortune_wheel#87]
I come across your package and upon initial testing, it's amazing - kudos!

I was wondering, does support exist for landing on a predefined result? for example, could I start the wheel with a defined end value and have the animation always land on that cell?

**Comment by kevlatus** [comment]
hi @peazz, as @programmador pointed out, this is exactly how this package works. Please have a look at the [example](https://pub.dev/packages/flutter_fortune_wheel/example) to see how values are provided to the wheel
